#!/bin/bash
#SBATCH --nodes=1
#SBATCH --tasks-per-node=8
#SBATCH --mem=16GB
#SBATCH --time=1:00:00
#SBATCH --job-name=dihydrogen
#SBATCH --account=def-ejohnson

module purge
module load StdEnv/2020
module load intel/2020.1.217 intelmpi/2019.7.217 imkl/2020.1.217 libxc/5.1.3

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export MKL_DYNAMIC=FALSE
ulimit -s unlimited

mpirun ~/projects/def-ejohnson/FHIaims/FHIaims_240920_1/build/aims.240507.scalapack.mpi.x </dev/null > h2.out 
